server:
  port: 8081
  servlet:
    context-path: /department

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/department_api?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: chimpanzee.rmq.cloudamqp.com
    port: 5672
    username: iobowxcf
    password: ir7KHgKnCDj2zhBizzrR-u30P_LfWBfr
    virtual-host: iobowxcf
    ssl:
      enabled: false

  jpa:
    hibernate:
      #ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      
flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
